plugin: aws_ec2
# Populate inventory with instances in these regions
regions:
  - us-east-1

keyed_groups:
  - key: tags.Name
    separator: ''
  - key: tags.environment
    separator: ''
    
compose:
  # Use the private IP address to connect to the host
  # (note: this does not modify inventory_hostname, which is set via I(hostnames))
  ansible_host: public_ip_address
