---

- name: copy static content
  copy:
    src: "{{ role_path }}/files/index.html"
    dest: "{{ nginx_root }}"

- name: update server.conf
  template:
    src: server.conf.j2
    dest: /etc/nginx/conf.d/server.conf
  notify:
    - restart nginx
