---

- name: enable amazon-linux-extras for nginx
  command: amazon-linux-extras enable nginx1

- name: install software
  package:
    name: nginx
    state: present

- name: place nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: copy ssl_certificate
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/etc/ssl/certs/{{ item }}"
  with_items:
    - 'notsecure.crt'
    - 'notsecure.key'

- name: ensure /etc/nginx/conf.d exists
  file:
    path: /etc/nginx/conf.d
    state: directory

- name: place server.conf
  template:
    src: server.conf.j2
    dest: /etc/nginx/conf.d/server.conf
  notify:
    - restart nginx

- name: start service
  service:
    name: nginx
    state: started
    enabled: yes
